### ISSUE TITLE
background-attachment: fixed causes page stutter

### ISSUE THREAD

**Issue by simondate** [KingsOnline/adapt-article-background#1]
[This attribute](https://github.com/KingsOnline/adapt-article-background/blob/master/js/adapt-article-background.js#L72) makes the image fixed in the page rather than scrolling through it and seems to cause some big frame rate issues.

**Comment by simondate** [comment]
@louisebennett I'll show this to you but suggest that we disable this attribute

**Comment by louisebennett** [comment]
@simondate Turns out the reason for this was that people were uploading 10-20mb images for the background, and that was too big for the page to deal with. Smaller ones seem to be working fine.

**Comment by simondate** [comment]
Good to know!

**Comment by canstudios-nicolaw** [comment]
Afternoon Simon & Louise,

Do either of you know why this attribute was added? Did it fix a bug or was it just for styling purposes? I think we would prefer if it was an optional attribute but we can overwrite it in the project CSS

Thanks

**Comment by simondate** [comment]
@canstudios-nicolaw It was present in the extension this was copied from https://github.com/davegosling/adapt-block-background

I agree having a setting would be nice. I'll add one this week!

**Comment by canstudios-nicolaw** [comment]
To me it looked like it got added in https://github.com/KingsOnline/adapt-article-background/commit/6ddb9fadc9ca5355056eb208d6eb98b26f9ab3a6 (I haven't noticed this attribute on the block background extension at all).

Thanks that would be fantastic! :), I've just shown this to our content team, they think it looks good, but probably wouldn't want this attribute set.

**Comment by canstudios-nicolaw** [comment]
Fantastic thank you Simon! :)

**Comment by simondate** [comment]
No worries :) Your Preview Editor looks amazing! Here's hoping that it becomes open source one day :crossed_fingers:
